//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 08:11:28 PM GFT 
//


package com.atos.lawws.webservice.xml.remitosdetalle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for detalleRemito complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detalleRemito">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="planta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fecha" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="punto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="knr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tmaimc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prefijo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="basico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sufijo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="proveedor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechaFis" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="remito" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="teileartgruppe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notaPedido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="code7227" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detalleRemito", propOrder = {
    "planta",
    "fecha",
    "punto",
    "knr",
    "tmaimc",
    "color",
    "prefijo",
    "basico",
    "sufijo",
    "cantidad",
    "proveedor",
    "fechaFis",
    "remito",
    "teileartgruppe",
    "notaPedido",
    "code7227"
})
public class DetalleRemito {

    @XmlElement(required = true)
    protected String planta;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fecha;
    @XmlElement(required = true)
    protected String punto;
    @XmlElement(required = true)
    protected String knr;
    @XmlElement(required = true)
    protected String tmaimc;
    @XmlElement(required = true)
    protected String color;
    @XmlElement(required = true)
    protected String prefijo;
    @XmlElement(required = true)
    protected String basico;
    @XmlElement(required = true)
    protected String sufijo;
    protected int cantidad;
    @XmlElement(required = true)
    protected String proveedor;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaFis;
    @XmlElement(required = true)
    protected String remito;
    @XmlElement(required = true)
    protected String teileartgruppe;
    @XmlElement(required = true)
    protected String notaPedido;
    @XmlElement(required = true)
    protected String code7227;

    /**
     * Gets the value of the planta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanta() {
        return planta;
    }

    /**
     * Sets the value of the planta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanta(String value) {
        this.planta = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the punto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPunto() {
        return punto;
    }

    /**
     * Sets the value of the punto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPunto(String value) {
        this.punto = value;
    }

    /**
     * Gets the value of the knr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKnr() {
        return knr;
    }

    /**
     * Sets the value of the knr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKnr(String value) {
        this.knr = value;
    }

    /**
     * Gets the value of the tmaimc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmaimc() {
        return tmaimc;
    }

    /**
     * Sets the value of the tmaimc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmaimc(String value) {
        this.tmaimc = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the prefijo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefijo() {
        return prefijo;
    }

    /**
     * Sets the value of the prefijo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefijo(String value) {
        this.prefijo = value;
    }

    /**
     * Gets the value of the basico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasico() {
        return basico;
    }

    /**
     * Sets the value of the basico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasico(String value) {
        this.basico = value;
    }

    /**
     * Gets the value of the sufijo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSufijo() {
        return sufijo;
    }

    /**
     * Sets the value of the sufijo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSufijo(String value) {
        this.sufijo = value;
    }

    /**
     * Gets the value of the cantidad property.
     * 
     */
    public int getCantidad() {
        return cantidad;
    }

    /**
     * Sets the value of the cantidad property.
     * 
     */
    public void setCantidad(int value) {
        this.cantidad = value;
    }

    /**
     * Gets the value of the proveedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProveedor() {
        return proveedor;
    }

    /**
     * Sets the value of the proveedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProveedor(String value) {
        this.proveedor = value;
    }

    /**
     * Gets the value of the fechaFis property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaFis() {
        return fechaFis;
    }

    /**
     * Sets the value of the fechaFis property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaFis(XMLGregorianCalendar value) {
        this.fechaFis = value;
    }

    /**
     * Gets the value of the remito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemito() {
        return remito;
    }

    /**
     * Sets the value of the remito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemito(String value) {
        this.remito = value;
    }

    /**
     * Gets the value of the teileartgruppe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeileartgruppe() {
        return teileartgruppe;
    }

    /**
     * Sets the value of the teileartgruppe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeileartgruppe(String value) {
        this.teileartgruppe = value;
    }

    /**
     * Gets the value of the notaPedido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotaPedido() {
        return notaPedido;
    }

    /**
     * Sets the value of the notaPedido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotaPedido(String value) {
        this.notaPedido = value;
    }

    /**
     * Gets the value of the code7227 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode7227() {
        return code7227;
    }

    /**
     * Sets the value of the code7227 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode7227(String value) {
        this.code7227 = value;
    }

}
