//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.19 at 08:11:28 PM GFT 
//


package com.atos.lawws.webservice.xml.actualizacionremitosdefinitivos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for remitoDefinitivo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="remitoDefinitivo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="proveedor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pieza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remitoProvFecha" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="remitoProvNumero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ptoVenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remitoDefFecha" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fechaCarga" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fechaValidacion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="idUsuario" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "remitoDefinitivo", propOrder = {
    "id",
    "proveedor",
    "pieza",
    "remitoProvFecha",
    "remitoProvNumero",
    "ptoVenta",
    "numero",
    "remitoDefFecha",
    "fechaCarga",
    "fechaValidacion",
    "idUsuario"
})
public class RemitoDefinitivo {

    protected int id;
    @XmlElement(required = true)
    protected String proveedor;
    @XmlElement(required = true)
    protected String pieza;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar remitoProvFecha;
    @XmlElement(required = true)
    protected String remitoProvNumero;
    @XmlElement(required = true)
    protected String ptoVenta;
    @XmlElement(required = true)
    protected String numero;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar remitoDefFecha;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaCarga;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaValidacion;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar idUsuario;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the proveedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProveedor() {
        return proveedor;
    }

    /**
     * Sets the value of the proveedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProveedor(String value) {
        this.proveedor = value;
    }

    /**
     * Gets the value of the pieza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPieza() {
        return pieza;
    }

    /**
     * Sets the value of the pieza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPieza(String value) {
        this.pieza = value;
    }

    /**
     * Gets the value of the remitoProvFecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRemitoProvFecha() {
        return remitoProvFecha;
    }

    /**
     * Sets the value of the remitoProvFecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRemitoProvFecha(XMLGregorianCalendar value) {
        this.remitoProvFecha = value;
    }

    /**
     * Gets the value of the remitoProvNumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemitoProvNumero() {
        return remitoProvNumero;
    }

    /**
     * Sets the value of the remitoProvNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemitoProvNumero(String value) {
        this.remitoProvNumero = value;
    }

    /**
     * Gets the value of the ptoVenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtoVenta() {
        return ptoVenta;
    }

    /**
     * Sets the value of the ptoVenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtoVenta(String value) {
        this.ptoVenta = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the remitoDefFecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRemitoDefFecha() {
        return remitoDefFecha;
    }

    /**
     * Sets the value of the remitoDefFecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRemitoDefFecha(XMLGregorianCalendar value) {
        this.remitoDefFecha = value;
    }

    /**
     * Gets the value of the fechaCarga property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaCarga() {
        return fechaCarga;
    }

    /**
     * Sets the value of the fechaCarga property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaCarga(XMLGregorianCalendar value) {
        this.fechaCarga = value;
    }

    /**
     * Gets the value of the fechaValidacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaValidacion() {
        return fechaValidacion;
    }

    /**
     * Sets the value of the fechaValidacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaValidacion(XMLGregorianCalendar value) {
        this.fechaValidacion = value;
    }

    /**
     * Gets the value of the idUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIdUsuario() {
        return idUsuario;
    }

    /**
     * Sets the value of the idUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIdUsuario(XMLGregorianCalendar value) {
        this.idUsuario = value;
    }

}
